### ISSUE TITLE
Phase 1: GitHub Search App

### ISSUE THREAD

**Issue by gabrielcarino** [learn-co-curriculum/phase-1-github-search-app#3]
### Canvas Link

https://learning.flatironschool.com/courses/4617/assignments/160491?module_item_id=384984

### Concern

This specific lesson and its sibling lessons inside the Apply your Learning module lack the green check marks that usually appear when an assignment is submitted. I believe, as a result, the completion is not being pushed to the https://base.flatironschool.com/milestones site as my milestone for the GitHub Search App shows incomplete, despite showing milestones after this is to be completed.

**Comment by professor-ben** [comment]
Hi Gabriel,

Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

They can work with you on some troubleshooting steps and they can send a ticket to us or Canvas support if those options don't work.

Thanks,
Ben
